
services:
  centrifugo:
    image: centrifugo/centrifugo:v6.6
    container_name: angular-desktop-ui-centrifugo
    restart: unless-stopped
    ports:
      - "8005:8000"  # HTTP/WebSocket endpoint
      - "8006:8001"  # Admin/internal endpoint (optional)
    environment:
      CENTRIFUGO_CLIENT_TOKEN_HMAC_SECRET_KEY: "secretkey"
      CENTRIFUGO_CLIENT_ALLOWED_ORIGINS: "*"
      CENTRIFUGO_HTTP_API_KEY: "apikey"
      CENTRIFUGO_LOG_LEVEL: "debug"
    volumes:
      - ./docker/centrifugo:/centrifugo
    command:
      - 'centrifugo'
      - '-c'
      - '/centrifugo/config.json'
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-desktop-ui-web
    ports:
      - "8888:4200"
    volumes:
      # Mount the entire project directory to /app
      - ./:/app
      # Use a named volume for node_modules to prevent host interference
      #- node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    # Use npm start with polling enabled
    command: npm start -- --poll 1000 --host 0.0.0.0
    # Restart on failure
    restart: unless-stopped
    networks:
      - app-network
volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
